if(DEFINED ENV{GITHUB_ACTIONS} AND "$ENV{GITHUB_ACTIONS}" STREQUAL "true")
    message(STATUS "Ejecutando dentro de GitHub Actions")
    set(RUNNING_IN_CI TRUE)
else()
    message(STATUS "Ejecutando de forma local")
    set(RUNNING_IN_CI FALSE)
endif()

if(RUNNING_IN_CI)
    target_compile_options(tests PRIVATE -frtti)
    target_compile_options(binaries PRIVATE -frtti)
endif()
