name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install LLVM and Clang 20
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "20"

     # - name: Configure project
      #  run: cmake --preset dev-full

     # - name: Build project
      #  run: cmake --build --preset dev-full --parallel "$(nproc)"

      - name: Run tests with coverage
        run: ./scripts/nicoleCompileAndRun.sh -t