name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies and clang 20
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake wget gnupg lsb-release llvm-20-dev
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          rm llvm.sh

      - name: Configure project
        run: |
          export CMAKE_PREFIX_PATH=/usr/lib/llvm-20
          cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_WARNINGS=OFF -DCMAKE_CXX_COMPILER=clang++-20 -DUSE_LLVM_CONFIG_20=ON

      - name: Build project
        run: cmake --build build -- -j$(nproc)

      - name: Run tests
        run: |
          chmod +x scripts/nicole.sh
          chmod +x scripts/nicoleCompile.sh
          chmod +x scripts/nicoleCompileAndRun.sh
          ./scripts/nicoleCompileAndRun.sh -t
