name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install LLVM and Clang 20
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "20"

      - name: Configure and Build
        run: |
          # Configurar con preset (genera CMakeCache.txt)
          cmake --preset dev-full
          # Ahora ya existe la caché; construimos
          cmake --build build --parallel "$(nproc)"

      - name: Run tests with coverage
        run: ./scripts/nicoleCompileAndRun.sh -t