name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install LLVM and Clang 20
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "20"

      - name: Configure project
        run: |
          export CMAKE_PREFIX_PATH="${{ env.LLVM_PATH:-./llvm }}/lib/cmake"
          cmake --preset dev-full -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build project
        run: |
          cmake --build build --parallel "$(nproc)"

      - name: Run tests with coverage
        run: ./scripts/nicoleCompileAndRun.sh -t