name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install LLVM and Clang 20
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "20"

      - name: Install ccache
        run: sudo apt-get install -y ccache

      - name: Run tests with coverage
        run: 
          export CXXFLAGS="-frtti"
          export CFLAGS="-frtti"
          ./scripts/nicoleCompileAndRun.sh -t