name: Build and Test

on:
  push:
    branches: [ parser ]
  pull_request:
    branches: [ parser ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang llvm

      - name: Configure project
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_WARNINGS=OFF

      - name: Build project
        run: cmake --build build -- -j$(nproc)

      - name: Run tests
        run: cd build && ctest --output-on-failure
